# Generated by Django 5.0 on 2026-03-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='material_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_materials/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link to an external video or embed (e.g. YouTube)', null=True),
        ),
    ]
